spring:
  # datasource
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/thinker-ws
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 100
